port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893
tproxy-port: 7895
ipv6: false
mode: rule
log-level: silent
allow-lan: true
external-controller: 0.0.0.0:9090
secret: ""
bind-address: "*"
unified-delay: true
profile:
  store-selected: true
dns:
  enable: true
  ipv6: false
  enhanced-mode: redir-host
  listen: 0.0.0.0:7874
  nameserver:
    - 8.8.8.8
    - 1.0.0.1
    - https://dns.google/dns-query
  fallback:
    - 1.1.1.1
    - 8.8.4.4
    - https://cloudflare-dns.com/dns-query
    - 112.215.203.254
  default-nameserver:
    - 8.8.8.8
    - 1.1.1.1
    - 112.215.203.254
proxies:
  - name: sg.goserver.pw-tls-masterssh-akuuuuuu
    server: vm.sg.goserver.pw
    port: 443
    type: vmess
    uuid: 6eed053e-8df4-4682-8b7e-f8a30186f13d
    alterId: 0
    cipher: auto
    tls: true
    skip-cert-verify: true
    servername: zoom.us
    network: ws
    ws-opts:
      path: /v2ray-vmess/tls
      headers:
        Host: zoom.us
    udp: true
proxy-groups:
  - name: FASTSSH-SSHKIT-HOWDY
    type: select
    proxies:
      - sg.goserver.pw-tls-masterssh-akuuuuuu
      - DIRECT
rules:
  - MATCH,FASTSSH-SSHKIT-HOWDY